name: bqsr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fontconfig > 2 
  - font-ttf-dejavu-sans-mono > 2
  - r-base
  - r-essentials
  - multiqc=1.7
  - gatk4=4.0.5.1
  - r-ggplot2=3.1.1
  - r-gplots=3.0.1
  - r-gsalib=2.1.0
  - r-essentials
  - r-reshape=0.8.8
